# vim: set ts=2 sw=2 sts=2:

---
debug: true
build:
  image: python:$$PY_VERSION
  commands:
    - echo foo
    - ( apt-get update && apt-get install -y git ) || ( apk update && apk add git )

matrix:
  PY_VERSION:
    - 2.7-wheezy
    - 3.3-wheezy
    - 3.4-wheezy
    - 3.5-alpine
